version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: bash -c "bundle install; bundler exec jekyll serve --watch --force_polling --port=8080 --host=0.0.0.0"
    image: amirpourmand/al-folio:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 127.0.0.1:8080:8080