version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: bundler exec jekyll serve --watch --config _config.docker.yml
    image: al-folio:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000